#!/bin/bash

TOUCHPANEL=(
# Radxa Display 8HD
goodix-ts
# Raspberry Pi Touch Display
fts_ts
)

# Map touch panel to DSI
for i in "${TOUCHPANEL[@]}"
do
    echo xinput --map-to-output "$i" DSI-1
done

# Run original setup script (if any)
exec "$@"
